apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendreverseproxy
spec:
  selector:
    matchLabels:
      app: frontendreverseproxy
  template:
    metadata:
      labels:
        app: frontendreverseproxy
    spec:
      containers:
        - name: frontendreverseproxy
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/frontendreverseproxy:4d5adb3
          ports:
            - containerPort: 80
          env: []
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-068565d4782ef18a5, subnet-0df2ab5a47b597aac"
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
  #  service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "http"
  #  service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/healthz"
  name: frontendreverseproxy-easytrade
  namespace: easytrade
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: frontendreverseproxy
  type: LoadBalancer



